server:
  port: 8801
  servlet:
    context-path: /test-demo

spring:
  application:
    name: test-demo12345566
  datasource:
    url: jdbc:mysql://localhost:3306/test-demo?autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 16
      auto-commit: true
      login-timeout: 30000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  cloud:
    #消息中间件配置
    stream:
      bindings:
        # 发送消息
        my-test-producer-message-out:
          destination: my-test-producer-message
          contentType: application/json
          group: myGroup
        # 接收消息
        my-test-producer-message-in:
          destination: my-test-producer-message
          contentType: application/json
          group: myGroup
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin


  # 热部署配置，只是对页面即时生效，对于java代码还是重启了项目
#  devtools:
#    restart:
#      # 设置开启热部署
#      enabled: true
#      # 重启目录
#      additional-paths: src/main/java
#      exclude: web-files/**
#  freemarker:
#    # 页面不加载缓存，修改即时生效
#    cache: false

#sql位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo
  configuration:
    # mybatis的延迟加载
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

#日志（有sql语句的打印）
logging:
  config: classpath:log-local.xml
  level:
    "com.example.demo": debug

#enable swagger
swagger:
  enable: true

#system:
#  test: true


