server:
  port: 8888

spring:
  application:
    name: test-demo
  datasource:
    url: jdbc:mysql://localhost:3306/test-demo?autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 16
      auto-commit: true
      login-timeout: 30000
      connection-timeout: 30000
      pool-name: DatebookHikariCP

#sql位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo

#日志（有sql语句的打印）
logging:
  config: classpath:log-local.xml
  level:
    "com.example.demo": debug


